export const GAME_CONSTANTS = {
  DEFAULT_DC: 12,
  BASE_AC: 10,
  CAST_MP_COST: 4,
  FLEE_DC: 10,
  GUARD_AC_BONUS: 2,
  DEFAULT_WEAPON_BASE: 5,
  CAST_WEAPON_BASE: 6,
  NARRATION_MAX_LENGTH: 300,
  NARRATION_MIN_LENGTH: 10,
  NPC_MEMORY_MAX_RECENT: 3,
  CONFIDENCE_THRESHOLD: 0.3,
  MAX_TURN_LOG_SIZE: 50,
} as const;

export const DEFAULT_START_LOCATION = 'loc_north_gate' as const;
